name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REACT_APP_DIR: codebase/rdicidr-0.1.0

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.REACT_APP_DIR }}

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: ${{ env.REACT_APP_DIR }}

      - name: Run lint
        run: npm run lint
        working-directory: ${{ env.REACT_APP_DIR }}

      - name: Build React App
        run: npm run build
        working-directory: ${{ env.REACT_APP_DIR }}

      - name: Archive production build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ${{ env.REACT_APP_DIR }}/build
